/** Run: npx tsx scripts/generate-seed.ts — outputs src/data/items.json */
import { writeFileSync } from "fs";
import { join } from "path";

const drugs: [string, string][] = [
  ["Lisinopril", "ACE inhibitor for high blood pressure"],
  ["Metformin", "First-line oral medication for type 2 diabetes"],
  ["Atorvastatin", "Statin that lowers LDL cholesterol"],
  ["Levothyroxine", "Synthetic thyroid hormone replacement"],
  ["Amlodipine", "Calcium channel blocker for hypertension"],
  ["Metoprolol", "Beta blocker for heart rate and blood pressure"],
  ["Omeprazole", "Proton pump inhibitor for acid reflux"],
  ["Simvastatin", "Statin used to reduce cardiovascular risk"],
  ["Losartan", "ARB for treating hypertension"],
  ["Gabapentin", "Anticonvulsant also used for nerve pain"],
  ["Hydrochlorothiazide", "Thiazide diuretic for fluid retention"],
  ["Sertraline", "SSRI antidepressant (Zoloft generic)"],
  ["Montelukast", "Leukotriene inhibitor for asthma"],
  ["Escitalopram", "SSRI for anxiety and depression"],
  ["Rosuvastatin", "Potent statin for hyperlipidemia"],
  ["Bupropion", "Atypical antidepressant and smoking cessation aid"],
  ["Pantoprazole", "PPI for GERD and stomach ulcers"],
  ["Furosemide", "Loop diuretic for edema and heart failure"],
  ["Trazodone", "Sedating antidepressant often used for insomnia"],
  ["Duloxetine", "SNRI for depression and fibromyalgia"],
  ["Fluticasone", "Inhaled corticosteroid for asthma"],
  ["Meloxicam", "NSAID for arthritis pain"],
  ["Carvedilol", "Beta blocker for heart failure"],
  ["Pravastatin", "Statin with fewer drug interactions"],
  ["Venlafaxine", "SNRI antidepressant"],
  ["Tramadol", "Weak opioid analgesic for moderate pain"],
  ["Albuterol", "Short-acting bronchodilator rescue inhaler"],
  ["Clopidogrel", "Antiplatelet agent after stent placement"],
  ["Potassium Chloride", "Electrolyte supplement for hypokalemia"],
  ["Cyclobenzaprine", "Muscle relaxant for acute spasms"],
  ["Methylprednisolone", "Corticosteroid for inflammation"],
  ["Citalopram", "SSRI antidepressant"],
  ["Azithromycin", "Macrolide antibiotic (Z-Pak)"],
  ["Amoxicillin", "Penicillin antibiotic for infections"],
  ["Prednisone", "Oral corticosteroid anti-inflammatory"],
  ["Ibuprofen", "NSAID for pain and fever"],
  ["Acetaminophen", "Analgesic and antipyretic (Tylenol)"],
  ["Alprazolam", "Benzodiazepine for acute anxiety"],
  ["Warfarin", "Vitamin K antagonist anticoagulant"],
  ["Apixaban", "Direct oral anticoagulant (Eliquis)"],
  ["Rivaroxaban", "Factor Xa inhibitor anticoagulant"],
  ["Insulin Glargine", "Long-acting basal insulin"],
  ["Empagliflozin", "SGLT2 inhibitor for diabetes and heart failure"],
  ["Semaglutide", "GLP-1 agonist for diabetes and weight loss"],
  ["Sitagliptin", "DPP-4 inhibitor for type 2 diabetes"],
  ["Glipizide", "Sulfonylurea stimulating insulin release"],
  ["Allopurinol", "Xanthine oxidase inhibitor for gout"],
  ["Colchicine", "Anti-inflammatory for acute gout flares"],
  ["Methotrexate", "DMARD for rheumatoid arthritis"],
  ["Hydroxychloroquine", "Antimalarial used in autoimmune disease"],
  ["Adalimumab", "TNF inhibitor biologic (Humira)"],
  ["Etanercept", "Biologic for psoriasis and arthritis"],
  ["Infliximab", "IV biologic TNF blocker"],
  ["Omalizumab", "Monoclonal antibody for severe asthma"],
  ["Dupilumab", "IL-4/IL-13 blocker for eczema"],
  ["Finasteride", "5-alpha reductase inhibitor for BPH"],
  ["Tamsulosin", "Alpha blocker for enlarged prostate"],
  ["Sildenafil", "PDE5 inhibitor for erectile dysfunction"],
  ["Tadalafil", "Long-acting PDE5 inhibitor"],
  ["Levofloxacin", "Fluoroquinolone antibiotic"],
  ["Ciprofloxacin", "Broad-spectrum fluoroquinolone"],
  ["Doxycycline", "Tetracycline antibiotic"],
  ["Clindamycin", "Lincosamide antibiotic"],
  ["Nitrofurantoin", "Antibiotic for uncomplicated UTIs"],
  ["Trimethoprim", "Antibiotic component of Bactrim"],
  ["Fluconazole", "Azole antifungal for yeast infections"],
  ["Acyclovir", "Antiviral for herpes viruses"],
  ["Valacyclovir", "Prodrug antiviral for shingles"],
  ["Oseltamivir", "Neuraminidase inhibitor for influenza"],
  ["Paxlovid", "Antiviral combination for COVID-19"],
  ["Remdesivir", "IV antiviral for severe COVID-19"],
  ["Nirmatrelvir", "Protease inhibitor component of Paxlovid"],
  ["Lamotrigine", "Mood stabilizer and anticonvulsant"],
  ["Lithium", "Mood stabilizer for bipolar disorder"],
  ["Quetiapine", "Atypical antipsychotic (Seroquel)"],
  ["Aripiprazole", "Partial dopamine agonist antipsychotic"],
  ["Olanzapine", "Atypical antipsychotic with metabolic risk"],
  ["Risperidone", "Typical atypical antipsychotic"],
  ["Haloperidol", "Typical antipsychotic for agitation"],
  ["Clonazepam", "Long-acting benzodiazepine"],
  ["Diazepam", "Benzodiazepine with muscle relaxant properties"],
  ["Zolpidem", "Non-benzodiazepine sleep aid"],
  ["Eszopiclone", "Sedative-hypnotic for insomnia"],
  ["Mirtazapine", "Tetracyclic antidepressant with appetite effect"],
  ["Buspirone", "Non-benzodiazepine anxiolytic"],
  ["Propranolol", "Beta blocker used for performance anxiety"],
  ["Spironolactone", "Potassium-sparing diuretic and anti-androgen"],
  ["Eplerenone", "Selective aldosterone antagonist"],
  ["Digoxin", "Cardiac glycoside for heart failure"],
  ["Amiodarone", "Antiarrhythmic with many side effects"],
  ["Diltiazem", "Calcium channel blocker for AFib rate control"],
  ["Verapamil", "Calcium channel blocker for hypertension"],
  ["Nitroglycerin", "Vasodilator for angina attacks"],
  ["Isosorbide", "Nitrate for angina prophylaxis"],
  ["Hydralazine", "Direct vasodilator for hypertension"],
  ["Chlorthalidone", "Thiazide-like diuretic"],
  ["Torsemide", "Loop diuretic alternative to furosemide"],
  ["Ethacrynic Acid", "Loop diuretic for sulfa allergy"],
  ["Famotidine", "H2 blocker for heartburn"],
  ["Ranitidine", "Former H2 blocker (largely withdrawn)"],
  ["Sucralfate", "Mucosal protectant for ulcers"],
  ["Ondansetron", "5-HT3 antagonist antiemetic"],
  ["Promethazine", "Phenothiazine antiemetic"],
  ["Metoclopramide", "Prokinetic antiemetic"],
  ["Loperamide", "Opioid agonist antidiarrheal"],
  ["Polyethylene Glycol", "Osmotic laxative (MiraLAX)"],
  ["Bisacodyl", "Stimulant laxative"],
  ["Docusate", "Stool softener"],
  ["Mesalamine", "5-ASA for inflammatory bowel disease"],
  ["Infliximab Biosimilar", "TNF inhibitor for Crohn's disease"],
  ["Budesonide", "Topical steroid for IBD"],
  ["Ursodiol", "Bile acid for gallstones"],
  ["Lactulose", "Osmotic laxative for hepatic encephalopathy"],
  ["Naloxone", "Opioid reversal agent"],
  ["Buprenorphine", "Partial opioid agonist for MAT"],
  ["Naltrexone", "Opioid antagonist for alcohol/opioid use"],
  ["Methadone", "Long-acting opioid for addiction treatment"],
  ["Nicotine Patch", "Nicotine replacement therapy"],
  ["Varenicline", "Partial nicotinic agonist for smoking cessation"],
  ["Orlistat", "Lipase inhibitor for weight loss"],
  ["Phentermine", "Appetite suppressant stimulant"],
  ["Levocetirizine", "Antihistamine for allergies"],
  ["Diphenhydramine", "First-generation sedating antihistamine"],
  ["Hydroxyzine", "Antihistamine used for itching and anxiety"],
  ["Prednisolone", "Steroid eye drop anti-inflammatory"],
  ["Timolol", "Beta blocker eye drop for glaucoma"],
  ["Latanoprost", "Prostaglandin analog for glaucoma"],
  ["Brimonidine", "Alpha-2 agonist glaucoma drop"],
  ["Tobramycin", "Aminoglycoside antibiotic drops"],
  ["Erythromycin", "Macrolide antibiotic"],
  ["Cephalexin", "First-generation cephalosporin"],
  ["Ceftriaxone", "Third-generation cephalosporin IV"],
  ["Vancomycin", "Glycopeptide for MRSA"],
  ["Linezolid", "Oxazolidinone for resistant infections"],
  ["Meropenem", "Carbapenem broad-spectrum antibiotic"],
  ["Piperacillin", "Extended-spectrum penicillin"],
  ["Gentamicin", "Aminoglycoside IV antibiotic"],
  ["Rifampin", "Antituberculosis antibiotic"],
  ["Isoniazid", "First-line TB medication"],
  ["Pyrazinamide", "TB treatment combination drug"],
  ["Ethambutol", "TB drug affecting vision"],
  ["PrEP Emtricitabine", "HIV prevention combination"],
  ["Tenofovir", "NRTI for HIV and hepatitis B"],
  ["Dolutegravir", "Integrase inhibitor for HIV"],
  ["Biktarvy", "Single-tablet HIV regimen"],
  ["Ledipasvir", "Hepatitis C antiviral component"],
  ["Sofosbuvir", "HCV polymerase inhibitor"],
  ["Ribavirin", "Antiviral for hepatitis C"],
  ["Interferon Beta", "MS disease-modifying therapy"],
  ["Fingolimod", "S1P modulator for multiple sclerosis"],
  ["Natalizumab", "Monoclonal antibody for MS"],
  ["Ocrelizumab", "Anti-CD20 for MS and lymphoma"],
  ["Levetiracetam", "Anticonvulsant (Keppra)"],
  ["Phenytoin", "Sodium channel antiepileptic"],
  ["Carbamazepine", "Anticonvulsant and mood stabilizer"],
  ["Topiramate", "Anticonvulsant used for migraines"],
  ["Sumatriptan", "Triptan for acute migraine"],
  ["Rizatriptan", "Fast-acting migraine triptan"],
  ["Prochlorperazine", "Antiemetic for migraine"],
  ["Erenumab", "CGRP monoclonal antibody for migraines"],
  ["Botulinum Toxin", "Neurotoxin for chronic migraine"],
  ["Denosumab", "RANKL inhibitor for osteoporosis"],
  ["Alendronate", "Bisphosphonate for bone density"],
  ["Calcitonin", "Hormone for bone pain"],
  ["Teriparatide", "PTH analog stimulating bone formation"],
  ["Leuprolide", "GnRH agonist for prostate cancer"],
  ["Tamoxifen", "SERM for breast cancer prevention"],
  ["Anastrozole", "Aromatase inhibitor for breast cancer"],
  ["Pembrolizumab", "PD-1 checkpoint inhibitor immunotherapy"],
  ["Nivolumab", "Anti-PD-1 cancer immunotherapy"],
  ["Bevacizumab", "Anti-VEGF monoclonal antibody"],
  ["Imatinib", "Tyrosine kinase inhibitor (Gleevec)"],
  ["Paclitaxel", "Chemotherapy microtubule stabilizer"],
  ["Carboplatin", "Platinum chemotherapy agent"],
  ["Cisplatin", "Platinum agent with nephrotoxicity"],
  ["Doxorubicin", "Anthracycline chemotherapy"],
  ["Methylphenidate", "Stimulant for ADHD"],
  ["Amphetamine Salts", "Mixed amphetamine ADHD treatment"],
  ["Atomoxetine", "Non-stimulant ADHD medication"],
  ["Guanfacine", "Alpha-2 agonist for ADHD"],
  ["Clonidine Patch", "Alpha agonist for ADHD and HTN"],
];

const pokemon: [string, string][] = [
  ["Pikachu", "Electric mouse Pokémon, mascot of the franchise"],
  ["Charizard", "Fire/Flying final evolution of Charmander"],
  ["Bulbasaur", "Grass/Poison starter from Kanto"],
  ["Squirtle", "Water-type starter turtle Pokémon"],
  ["Mewtwo", "Genetically engineered Psychic legendary"],
  ["Mew", "Mythical ancestor of all Pokémon"],
  ["Eevee", "Evolution Pokémon with many branched evolutions"],
  ["Gyarados", "Violent Water/Flying serpent evolution of Magikarp"],
  ["Snorlax", "Normal-type sleeping giant blocking routes"],
  ["Dragonite", "Friendly dragon final form of Dratini"],
  ["Gengar", "Ghost/Poison mischievous shadow Pokémon"],
  ["Alakazam", "Psychic spoon-bending final evolution"],
  ["Machamp", "Four-armed Fighting-type powerhouse"],
  ["Arcanine", "Legendary-like Fire dog Pokémon"],
  ["Lapras", "Gentle Water/Ice transport Pokémon"],
  ["Articuno", "Ice/Flying legendary bird of Kanto"],
  ["Zapdos", "Electric/Flying legendary bird"],
  ["Moltres", "Fire/Flying legendary bird"],
  ["Ditto", "Normal-type that transforms into others"],
  ["Jigglypuff", "Normal/Fairy singer from anime"],
  ["Meowth", "Normal cat Pokémon, Team Rocket companion"],
  ["Psyduck", "Water-type headache-prone duck"],
  ["Growlithe", "Loyal Fire puppy Pokémon"],
  ["Abra", "Psychic that teleports when threatened"],
  ["Machop", "Fighting-type muscle training Pokémon"],
  ["Bellsprout", "Grass/Poison vine Pokémon"],
  ["Geodude", "Rock/Ground floating rock Pokémon"],
  ["Magnemite", "Electric/Steel magnet Pokémon"],
  ["Grimer", "Poison sludge from polluted waters"],
  ["Gastly", "Ghost/Poison gas Pokémon"],
  ["Onix", "Rock serpent, later can become Steelix"],
  ["Hypno", "Psychic pendulum hypnotist"],
  ["Krabby", "Water crab found on beaches"],
  ["Voltorb", "Electric sphere that explodes"],
  ["Exeggcute", "Grass/Psychic cluster of eggs"],
  ["Cubone", "Ground-type wearing its mother's skull"],
  ["Hitmonlee", "Fighting kicking specialist"],
  ["Hitmonchan", "Fighting punching specialist"],
  ["Lickitung", "Normal-type with a huge tongue"],
  ["Koffing", "Poison gas balloon Pokémon"],
  ["Rhyhorn", "Rock/Ground rhino Pokémon"],
  ["Chansey", "Normal healer from Pokémon Centers"],
  ["Tangela", "Grass-type hidden in blue vines"],
  ["Kangaskhan", "Parental Normal-type with a joey"],
  ["Horsea", "Water seahorse Pokémon"],
  ["Goldeen", "Water goldfish with horn"],
  ["Staryu", "Water star with regenerating core"],
  ["Mr. Mime", "Psychic/Fairy barrier performer"],
  ["Scyther", "Bug/Flying mantis swordsman"],
  ["Jynx", "Ice/Psychic humanoid Pokémon"],
  ["Electabuzz", "Electric tiger Pokémon"],
  ["Magmar", "Fire duck-billed Pokémon"],
  ["Pinsir", "Bug pincer beetle"],
  ["Tauros", "Normal bull herd Pokémon"],
  ["Magikarp", "Weak Water fish that splashes"],
  ["Dodrio", "Normal/Flying three-headed bird"],
  ["Aerodactyl", "Rock/Flying fossil pterosaur"],
  ["Kabutops", "Rock/Water fossil predator"],
  ["Aerodactyl Fossil", "Revived ancient flying predator"],
  ["Dratini", "Dragon serpent that sheds skin"],
  ["Chikorita", "Johto Grass starter"],
  ["Cyndaquil", "Johto Fire starter echidna"],
  ["Totodile", "Johto Water crocodile starter"],
  ["Feraligatr", "Final Water croc evolution"],
  ["Typhlosion", "Fire badger final starter evolution"],
  ["Meganium", "Grass flower dinosaur final form"],
  ["Crobat", "Fast Poison/Flying bat evolution"],
  ["Ampharos", "Electric lighthouse sheep Pokémon"],
  ["Bellossom", "Grass dancer evolved from Oddish line"],
  ["Azumarill", "Water/Fairy aqua rabbit"],
  ["Sudowoodo", "Rock mimic that looks like a tree"],
  ["Politoed", "Water/Fairy frog king"],
  ["Espeon", "Psychic evolution of Eevee via friendship"],
  ["Umbreon", "Dark evolution of Eevee at night"],
  ["Slowking", "Water/Psychic royal Slowpoke"],
  ["Unown", "Psychic alphabet symbol Pokémon"],
  ["Wobbuffet", "Psychic counter-attacker"],
  ["Girafarig", "Normal/Psychic giraffe with tail head"],
  ["Pineco", "Bug that becomes Forretress"],
  ["Gligar", "Ground/Flying scorpion glider"],
  ["Steelix", "Steel/Ground giant serpent"],
  ["Scizor", "Bug/Steel metal mantis"],
  ["Heracross", "Bug/Fighting horn beetle"],
  ["Sneasel", "Dark/Ice clawed weasel"],
  ["Teddiursa", "Normal bear cub"],
  ["Ursaring", "Normal bear evolved form"],
  ["Slugma", "Fire slug molten Pokémon"],
  ["Houndour", "Dark/Fire hound puppy"],
  ["Houndoom", "Dark/Fire hellhound evolution"],
  ["Kingdra", "Water/Dragon seahorse king"],
  ["Phanpy", "Ground elephant calf"],
  ["Donphan", "Ground armored elephant"],
  ["Porygon2", "Normal upgraded virtual Pokémon"],
  ["Stantler", "Normal reindeer with hypnotic antlers"],
  ["Smeargle", "Normal painter with Sketch move"],
  ["Tyrogue", "Fighting baby that branches"],
  ["Hitmontop", "Fighting spinning top fighter"],
  ["Miltank", "Normal milk-producing cow"],
  ["Blissey", "Normal ultimate Chansey evolution"],
  ["Raikou", "Electric legendary beast of Johto"],
  ["Entei", "Fire legendary beast"],
  ["Suicune", "Water legendary beast"],
  ["Larvitar", "Rock/Ground pupa dinosaur"],
  ["Tyranitar", "Rock/Dark pseudo-legendary kaiju"],
  ["Lugia", "Psychic/Flying guardian of the seas"],
  ["Ho-Oh", "Fire/Flying rainbow bird legendary"],
  ["Celebi", "Psychic/Grass time-travel myth"],
  ["Treecko", "Hoenn Grass gecko starter"],
  ["Torchic", "Hoenn Fire chick starter"],
  ["Mudkip", "Hoenn Water mudfish starter"],
  ["Blaziken", "Fire/Fighting final Torchic evolution"],
  ["Swampert", "Water/Ground final Mudkip evolution"],
  ["Sceptile", "Grass final Treecko evolution"],
  ["Gardevoir", "Psychic/Fairy guardian evolution"],
  ["Sableye", "Dark/Ghost gem eater"],
  ["Mawile", "Steel/Fairy deceiver with huge jaws"],
  ["Aggron", "Steel/Rock armored titan"],
  ["Flygon", "Ground/Dragon desert spirit"],
  ["Milotic", "Water serpent of beauty"],
  ["Castform", "Normal weather-transform Pokémon"],
  ["Kecleon", "Normal color-changing chameleon"],
  ["Banette", "Ghost possessed doll"],
  ["Duskull", "Ghost skull Pokémon"],
  ["Absol", "Dark disaster-warning Pokémon"],
  ["Walrein", "Ice/Water walrus fully evolved"],
  ["Clamperl", "Water bivalve that branches evolve"],
  ["Relicanth", "Water/Rock living fossil fish"],
  ["Luvdisc", "Water heart-shaped fish"],
  ["Regirock", "Rock golem legendary"],
  ["Regice", "Ice golem legendary"],
  ["Registeel", "Steel golem legendary"],
  ["Latias", "Dragon/Psychic Eon duo"],
  ["Latios", "Dragon/Psychic Eon bird"],
  ["Kyogre", "Water primal legendary"],
  ["Groudon", "Ground primal legendary"],
  ["Rayquaza", "Dragon/Flying sky lord"],
  ["Deoxys", "Psychic alien virus Pokémon"],
  ["Turtwig", "Sinnoh Grass turtle starter"],
  ["Chimchar", "Sinnoh Fire monkey starter"],
  ["Piplup", "Sinnoh Water penguin starter"],
  ["Infernape", "Fire/Fighting final Chimchar"],
  ["Empoleon", "Water/Steel final Piplup"],
  ["Torterra", "Grass/Ground continent on back"],
  ["Luxray", "Electric lion predator"],
  ["Roserade", "Grass/Poison bouquet Pokémon"],
  ["Rampardos", "Rock headbutt fossil"],
  ["Bastiodon", "Rock/Steel shield fossil"],
  ["Vespiquen", "Bug/Flying queen bee"],
  ["Pachirisu", "Electric squirrel"],
  ["Floatzel", "Water weasel swimmer"],
  ["Gastrodon", "Water/Ground sea slug"],
  ["Ambipom", "Normal double-tail monkey"],
  ["Drifblim", "Ghost/Flying hot air balloon"],
  ["Mismagius", "Ghost witch evolution"],
  ["Honchkrow", "Dark/Flying mafia crow"],
  ["Skuntank", "Poison/Dark skunk"],
  ["Bronzong", "Steel/Psychic bell Pokémon"],
  ["Spiritomb", "Ghost/Dark forbidden spirit"],
  ["Garchomp", "Dragon/Ground pseudo-legendary"],
  ["Lucario", "Fighting/Steel aura Pokémon"],
  ["Riolu", "Fighting baby aura Pokémon"],
  ["Hippowdon", "Ground hippo"],
  ["Drapion", "Poison/Dark scorpion"],
  ["Carnivine", "Grass pitcher plant"],
  ["Finneon", "Water wingfish"],
  ["Snover", "Grass/Ice snowy tree"],
  ["Weavile", "Dark/Ice evolved Sneasel"],
  ["Magnezone", "Electric/Steel UFO magnet"],
  ["Electivire", "Electric evolved Electabuzz"],
  ["Magmortar", "Fire evolved Magmar"],
  ["Yanmega", "Bug/Flying ancient dragonfly"],
  ["Leafeon", "Grass Eeveelution"],
  ["Glaceon", "Ice Eeveelution"],
  ["Gliscor", "Ground/Flying evolved Gligar"],
  ["Mamoswine", "Ice/Ground woolly mammoth"],
  ["Gallade", "Psychic/Fighting Gardevoir counterpart"],
  ["Probopass", "Rock/Steel nose compass"],
  ["Dusknoir", "Ghost hand-from-shadow evolution"],
  ["Froslass", "Ice/Ghost female Snorunt evolution"],
  ["Rotom", "Electric ghost that possesses appliances"],
  ["Uxie", "Psychic lake guardian of knowledge"],
  ["Mesprit", "Psychic lake guardian of emotion"],
  ["Azelf", "Psychic lake guardian of willpower"],
  ["Dialga", "Steel/Dragon time legendary"],
  ["Palkia", "Water/Dragon space legendary"],
  ["Giratina", "Ghost/Dragon antimatter legendary"],
  ["Darkrai", "Dark nightmare legendary"],
  ["Shaymin", "Grass myth with Sky Forme"],
  ["Arceus", "Normal creator deity Pokémon"],
  ["Victini", "Psychic/Fire victory myth"],
  ["Zorua", "Dark fox illusionist"],
  ["Zoroark", "Dark fox master of illusions"],
  ["Gothitelle", "Psychic staring Pokémon"],
  ["Reuniclus", "Psychic cell colony"],
  ["Swanna", "Water/Flying swan"],
  ["Vanilluxe", "Ice double-scoop snow Pokémon"],
  ["Sawsbuck", "Normal/Grass seasonal deer"],
  ["Emolga", "Electric/Flying flying squirrel"],
  ["Krookodile", "Ground/Dark intimidation croc"],
  ["Darmanitan", "Fire zen mode gorilla"],
  ["Scrafty", "Dark/Fighting hoodlum lizard"],
  ["Archeops", "Rock/Flying ancient bird"],
  ["Zorua Hisuian", "Normal/Ghost regional fox"],
  ["Garbodor", "Poison trash heap"],
  ["Zekrom", "Dragon/Electric black dragon"],
  ["Reshiram", "Dragon/Fire white dragon"],
  ["Kyurem", "Dragon/Ice boundary dragon"],
  ["Meloetta", "Normal/Psychic musical myth"],
  ["Genesect", "Bug/Steel modified ancient insect"],
  ["Xerneas", "Fairy life legendary"],
  ["Yveltal", "Dark destruction legendary"],
  ["Zygarde", "Dragon/Ground order legendary"],
  ["Diancie", "Rock/Fairy myth"],
  ["Hoopa", "Psychic/Ghost genie myth"],
  ["Volcanion", "Fire/Water steam myth"],
  ["Rowlet", "Alola Grass owl starter"],
  ["Litten", "Alola Fire cat starter"],
  ["Popplio", "Alola Water sea lion starter"],
  ["Decidueye", "Grass/Ghost archer owl"],
  ["Incineroar", "Fire/Dark wrestler cat"],
  ["Primarina", "Water/Fairy siren starter final"],
  ["Lycanroc", "Rock wolf with formes"],
  ["Mimikyu", "Ghost/Fairy Pikachu disguise"],
  ["Bewear", "Normal/Fighting hug bear"],
  ["Kommo-o", "Dragon/Fighting scaled fighter"],
  ["Tapu Koko", "Electric/Fairy island guardian"],
  ["Solgaleo", "Psychic/Steel sunne legendary"],
  ["Lunala", "Psychic/Ghost moone legendary"],
  ["Necrozma", "Psychic light-devouring legendary"],
  ["Marshadow", "Fighting/Ghost shadow myth"],
  ["Zeraora", "Electric thunder cat myth"],
  ["Grookey", "Galar Grass chimp starter"],
  ["Scorbunny", "Galar Fire rabbit starter"],
  ["Sobble", "Galar Water lizard starter"],
  ["Rillaboom", "Grass drummer gorilla"],
  ["Cinderace", "Fire soccer rabbit"],
  ["Inteleon", "Water spy lizard"],
  ["Corviknight", "Flying/Steel taxi raven"],
  ["Orbeetle", "Bug/Psychic intelligent beetle"],
  ["Coalossal", "Rock/Fire coal titan"],
  ["Flapple", "Grass apple dragon"],
  ["Appletun", "Grass/Dragon sweet apple"],
  ["Toxtricity", "Electric/Poison punk rocker"],
  ["Dragapult", "Dragon/Ghost stealth bomber"],
  ["Zacian", "Fairy sword legendary wolf"],
  ["Zamazenta", "Fighting shield legendary wolf"],
  ["Eternatus", "Poison/Dragon giant alien dragon"],
  ["Kubfu", "Fighting martial cub"],
  ["Urshifu", "Fighting/Dark or Water kung fu bear"],
  ["Regieleki", "Electric energy legendary"],
  ["Regidrago", "Dragon energy legendary"],
  ["Glastrier", "Ice horse legendary"],
  ["Spectrier", "Ghost horse legendary"],
  ["Calyrex", "Psychic/Grass king legendary"],
  ["Sprigatito", "Paldea Grass cat starter"],
  ["Fuecoco", "Paldea Fire croc starter"],
  ["Quaxly", "Paldea Water duck starter"],
  ["Meowscarada", "Grass/Dark magician cat"],
  ["Skeledirge", "Fire/Ghost singer croc"],
  ["Quaquaval", "Water/Fighting dancer duck"],
  ["Lechonk", "Normal piglet"],
  ["Oinkologne", "Normal pig evolution"],
  ["Pawmi", "Electric mouse cousin"],
  ["Pawmot", "Electric/Fighting evolved Pawmi"],
  ["Tandemaus", "Normal pair of mice"],
  ["Maushold", "Normal family of mice"],
  ["Gholdengo", "Steel/Ghost coin stack"],
  ["Annihilape", "Fighting/Ghost rage ape"],
  ["Kingambit", "Dark/Steel chess king"],
  ["Iron Valiant", "Fairy/Fighting paradox"],
  ["Roaring Moon", "Dragon/Dark paradox salamence"],
  ["Walking Wake", "Water/Dragon paradox Suicune"],
  ["Koraidon", "Fighting/Dragon ancient legend"],
  ["Miraidon", "Electric/Dragon future legend"],
  ["Ogerpon", "Grass mask legendary"],
  ["Terapagos", "Normal terastal turtle legend"],
  ["Pecharunt", "Poison/Ghost mythical peach"],
];

function slugify(name: string) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

const DRUG_LIMIT = 150;
const POKEMON_LIMIT = 150;

const items = [
  ...drugs.slice(0, DRUG_LIMIT).map(([name, description], i) => ({
    id: `drug-${i + 1}`,
    name,
    category: "drug" as const,
    slug: slugify(name),
    description,
  })),
  ...pokemon.slice(0, POKEMON_LIMIT).map(([name, description], i) => ({
    id: `pokemon-${i + 1}`,
    name,
    category: "pokemon" as const,
    slug: slugify(name),
    description,
  })),
];

const out = join(process.cwd(), "src", "data", "items.json");
writeFileSync(out, JSON.stringify(items, null, 2));
console.log(`Wrote ${items.length} items to ${out}`);
